CREATE TABLE BBOARD (
	NUM NUMBER(5) PRIMARY KEY,
	PASS VARCHAR2(30),
	NAME VARCHAR2(30),
	EMAIL VARCHAR2(30),
	TITLE VARCHAR2(30),
	CONTENT VARCHAR2(1000),
	READCOUNT NUMBER(4) DEFAULT 0,
	WRITEDATE DATE DEFAULT SYSDATE
	);
	

CREATE SEQUENCE BOARD_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO BBOARD(NUM, NAME, EMAIL, PASS, TITLE, CONTENT)
VALUES(BOARD_SEQ.NEXTVAL, '람지쿠','ramzikoo@adg.com','1234','최고심잠옷결제','성공적');

SELECT * FROM BBOARD